version: "3.9"
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: "simple_bank"
      POSTGRES_USER: "klengs"
      POSTGRES_PASSWORD: "Qwerty123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    # volumes:
    #   - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://klengs:Qwerty123@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]