// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) (Account, error)
	GetAccountByID(ctx context.Context, id int64) (Account, error)
	GetAllAccounts(ctx context.Context, arg GetAllAccountsParams) ([]Account, error)
	GetAllEntries(ctx context.Context, arg GetAllEntriesParams) ([]Entry, error)
	GetEntriesByAccountID(ctx context.Context, arg GetEntriesByAccountIDParams) ([]Entry, error)
	GetEntryByID(ctx context.Context, id int64) (Entry, error)
	GetTransferByFromToIDS(ctx context.Context, arg GetTransferByFromToIDSParams) ([]Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
